-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 10:52:00 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema domotica_poo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema domotica_poo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `domotica_poo` DEFAULT CHARACTER SET utf8 ;
USE `domotica_poo` ;

-- -----------------------------------------------------
-- Table `domotica_poo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotica_poo`.`users` ;

CREATE TABLE IF NOT EXISTS `domotica_poo`.`users` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` LONGTEXT NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iduser_UNIQUE` ON `domotica_poo`.`users` (`iduser` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE` ON `domotica_poo`.`users` (`email` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `domotica_poo`.`houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotica_poo`.`houses` ;

CREATE TABLE IF NOT EXISTS `domotica_poo`.`houses` (
  `idhouse` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idhouse`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idhouses_UNIQUE` ON `domotica_poo`.`houses` (`idhouse` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `domotica_poo`.`area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotica_poo`.`area` ;

CREATE TABLE IF NOT EXISTS `domotica_poo`.`area` (
  `idarea` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `idhouses` INT NULL,
  PRIMARY KEY (`idarea`),
  CONSTRAINT `idhouses`
    FOREIGN KEY (`idhouses`)
    REFERENCES `domotica_poo`.`houses` (`idhouse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idarea_UNIQUE` ON `domotica_poo`.`area` (`idarea` ASC) VISIBLE;

CREATE INDEX `idhouses_idx` ON `domotica_poo`.`area` (`idhouses` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `domotica_poo`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotica_poo`.`room` ;

CREATE TABLE IF NOT EXISTS `domotica_poo`.`room` (
  `idroom` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `idarea` INT NOT NULL,
  PRIMARY KEY (`idroom`),
  CONSTRAINT `idarea`
    FOREIGN KEY (`idarea`)
    REFERENCES `domotica_poo`.`area` (`idarea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idroom_UNIQUE` ON `domotica_poo`.`room` (`idroom` ASC) VISIBLE;

CREATE INDEX `idarea_idx` ON `domotica_poo`.`room` (`idarea` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `domotica_poo`.`devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `domotica_poo`.`devices` ;

CREATE TABLE IF NOT EXISTS `domotica_poo`.`devices` (
  `iddevice` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `state` TINYINT NOT NULL,
  `idroom` INT NOT NULL,
  PRIMARY KEY (`iddevice`),
  CONSTRAINT `idroom`
    FOREIGN KEY (`idroom`)
    REFERENCES `domotica_poo`.`room` (`idroom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `iddevices_UNIQUE` ON `domotica_poo`.`devices` (`iddevice` ASC) VISIBLE;

CREATE INDEX `idroom_idx` ON `domotica_poo`.`devices` (`idroom` ASC) VISIBLE;

CREATE INDEX `iduser_idx` ON `domotica_poo`.`devices` (`iduser` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
